version: '3'

services:
  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    volumes:
      - domjudge_mariadb:/var/lib/mysql
  
  domserver:
    image: alphabit_domserver:0.2
    environment:
      - CONTAINER_TIMEZONE=Africa/Algiers
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
      - WAIT_HOSTS=mariadb:3306
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 80:80
    depends_on:
      - mariadb

  judgehost:
    image: alphabit_judgehost:0.2
    hostname: alphabit_judgehost0
    environment:
      - CONTAINER_TIMEZONE=Africa/Algiers
      - JUDGEDAEMON_USERNAME=judgehost
      - JUDGEDAEMON_PASSWORD=password
      - DOMSERVER_BASEURL=http://domserver/
      - DAEMON_ID=0
      - WAIT_HOSTS=domserver:80
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    depends_on:
      - domserver
    privileged: true


volumes:
  domjudge_mariadb:
